# Generated by Django 5.2.7 on 2025-10-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recorridos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('recorridos', models.ManyToManyField(to='recorridos.recorrido')),
            ],
        ),
    ]
