# Generated by Django 5.2.7 on 2025-11-14 16:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('NATURAL', 'Natural'), ('CULTURAL', 'Cultural'), ('GASTRONOMIA', 'Gastronimia'), ('RELIGIOSO', 'Religiosa')], default='CULTURAL', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Punto turístico',
                'verbose_name_plural': 'Puntos turísticos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=7, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('capacidad', models.PositiveIntegerField(default=20)),
            ],
            options={
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('hora_salida', models.TimeField()),
                ('hora_llegada', models.TimeField()),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('puntos_turisticos', models.ManyToManyField(blank=True, related_name='recorridos', to='reservas.puntoturistico')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('forma_de_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRASNFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('QR', 'Codigo QR')], default='EFECTIVO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_reserva', models.DateField()),
                ('cantidad_personas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.recorrido')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
