# Generated by Django 5.2.7 on 2025-10-15 18:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recorridos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('cant_personas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.BooleanField(default=True)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.formapago')),
                ('recorrido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='recorridos.recorrido')),
            ],
        ),
    ]
