# Generated by Django 5.2.7 on 2025-10-16 19:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('hora_salida', models.TimeField()),
                ('hora_llegada', models.TimeField()),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.CreateModel(
            name='RecorridoParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('tiempo_espera_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.parada')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.recorrido')),
            ],
            options={
                'ordering': ['recorrido', 'orden'],
                'unique_together': {('recorrido', 'orden')},
            },
        ),
        migrations.AddField(
            model_name='recorrido',
            name='paradas',
            field=models.ManyToManyField(related_name='recorridos', through='reservas.RecorridoParada', to='reservas.parada'),
        ),
        migrations.CreateModel(
            name='UnidadTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=7)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('recorrido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='reservas.recorrido')),
            ],
            options={
                'ordering': ['patente'],
            },
        ),
    ]
