# Generated by Django 5.2.7 on 2025-10-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorrido',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
