# Generated by Django 5.2.7 on 2025-10-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
