# Generated by Django 5.2.7 on 2025-10-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadtransporte',
            name='patente',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
