# Generated by Django 5.2.7 on 2025-10-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puntoturistico',
            options={'ordering': ['nombre'], 'verbose_name': 'Punto turístico', 'verbose_name_plural': 'Puntos turísticos'},
        ),
        migrations.RemoveField(
            model_name='puntoturistico',
            name='decripcion',
        ),
        migrations.AddField(
            model_name='puntoturistico',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='puntoturistico',
            name='categoria',
            field=models.CharField(choices=[('NATURAL', 'Natural'), ('CULTURAL', 'Cultural'), ('GASTRONOMIA', 'Gastronimia'), ('RELIGIOSO', 'Religiosa')], default='CULTURAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='puntoturistico',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
