# Generated by Django 5.2.7 on 2025-10-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_recorrido_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='forma_de_pago',
            field=models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('TRASNFERENCIA', 'TRASNFERENCIA'), ('TARJETA', 'TARJETA'), ('QR', 'QR')], default='EFECTIVO', max_length=20),
        ),
    ]
