# Generated by Django 5.2.7 on 2025-10-17 03:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_unidadtransporte_patente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('observaciones', models.TextField()),
                ('recorridos', models.ManyToManyField(related_name='itinerarios', to='reservas.recorrido')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cantidad_personas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.recorrido')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
