# Generated by Django 5.2.7 on 2025-10-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_itinerario_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='recorrido',
        ),
        migrations.AddField(
            model_name='reserva',
            name='recorrido',
            field=models.ManyToManyField(related_name='reservas', to='reservas.recorrido'),
        ),
    ]
