# Generated by Django 5.2.7 on 2025-10-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paradas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('horaInicio', models.TimeField(auto_now_add=True)),
                ('horaFin', models.TimeField(auto_now_add=True)),
                ('precio', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('paradas', models.ManyToManyField(to='paradas.parada')),
            ],
        ),
    ]
